
#include rose-pine.conf
font_size 12.5
# font_family Iosevka Term Extended
window_margin_width 0
remember_window_size no
background_opacity 0.9
window_padding_width 3 7 3 7 

clipboard_control write-clipboard write-primary no-append

# BEGIN_KITTY_FONTS
font_family      family='JetBrains Mono' style=Medium
bold_font        auto
italic_font      auto
bold_italic_font auto
map ctrl+plus change_font_size current +0.5 
map ctrl+minus change_font_size current -0.5 

# END_KITTY_FONTS


# BEGIN_WINDOW_LAYOUT
confirm_os_window_close 10
# END_WINDOW_LAYOUT
# BEGIN_KITTY_THEME
# Everforest Dark Hard
include current-theme.conf
# END_KITTY_THEME
#
# CUSTOM KEYBINDS
map ctrl+enter launch --type=os-window --cwd=current
