# Set true color
set-option -sa terminal-overrides ",xterm*:Tc"
#set -g mouse on

# Set prefix
unbind C-b
set -g prefix M-F12
bind-key M-F12 send-prefix


#### akl rebind ####
# Shfit alt vim keys to switch windows
bind -n M-h next-window
bind -n M-a previous-window

# New instance
bind-key enter run-shell "kitty --detach tmux attach-session -t #S"

# Bindings for Copy Mode (navigation)
bind-key -T copy-mode-vi k send-keys -X cursor-left
bind-key -T copy-mode-vi h send-keys -X cursor-down
bind-key -T copy-mode-vi a send-keys -X cursor-up
bind-key -T copy-mode-vi e send-keys -X cursor-right
# Start selection with 'v' (standard) or your layout's equivalent
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Copy with 'y' (yank)
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Use Prefix + Space to enter copy mode
bind space copy-mode
# Toggle status bar visibility with Prefix + b
bind-key b set-option -g status 



set -g update-environment "HYPRLAND_INSTANCE_SIGNATURE DISPLAY WAYLAND_DISPLAY SWAYSOCK SSH_AUTH_SOCK"
# status bar
# set -g status
set -g focus-events on
set -g status-style bg=default
# set -g status-left '#(cat #{socket_path}-\#{session_id}-vimbridge)'
set -g status-left '%H:%M #S'
set -g status-left-length 99
# set -g status-right '#(cat #{socket_path}-\#{session_id}-vimbridge-R)'
set -g status-right '#(cat /sys/class/power_supply/BAT0/capacity)% %d-%b-%y'
set -g status-right-length 99
set -g status-justify centre
set -g status-interval 5
set -g status-position top
#Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'laktak/extrakto'
set -g @plugin 'omerxx/tmux-sessionx'


# vim-tmux-navigator remap
set -g @vim_navigator_mapping_left "C-k"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-e"
set -g @vim_navigator_mapping_up "C-a"
set -g @vim_navigator_mapping_down "C-h"
# tmux-sessionx
set -g @sessionx-bind 'e'

# tmux-continuum 
# set -g @continuum-boot-options 'kitty'
# set -g @continuum-boot 'on'
# set -g @continuum-restore 'on'

run-shell '/usr/share/tmux-plugin-manager/tpm'

