[ids]
*
m:32c2:0001:8d8a7bdb
m:32c2:0001:0206ecdc
include maya



[global]
overload_tap_timeout= 170
oneshot_timeout=3000
macro_sequence_timeout=10000
chord_timeout= 70

[main]
# Maps capslock to escape when pressed and control when held.
capslock = overloadt(nav, esc, 175)
compose = f11
playpause = toggle(togglerandom)
# esc to ` for 60% keyboard
esc = `
-=f11
==]
# Homerow mods
#i = overloadt2(shiftextras, o, 170)
#a = lettermod(control, n, 60, 135)
#s = lettermod(alt, r, 60, 135)
#d = overloadt2(shift, t, 135)
#f = lettermod(meta, s, 60, 135h
i = lettermod(shiftextras, o, 90, 155)
a = lettermod(control, n, 90, 155)
s = lettermod(altmain, r, 90, 155)
d = lettermod(shiftmain, t, 90, 155)
f = lettermod(metamain, s, 90, 155)
stopcd = toggle(nodelete)


g = lettermod(controlextra, v, 90, 155)
e = lettermod(extra, d, 60, 145)
w = lettermod(w_extras, l, 90, 155)
# Reassign shift to custom layer
leftshift = overloadt2(vim, A-f12, 175)
rightshift = macro(A-f12)
leftshift+rightshift = toggle(shift)
leftalt = macro(A-f12)
rightalt = macro(A-f12)

# Chords v2

[altmain:A]
[shiftmain:S]
d = t
space = macro(C-space)

[metamain:M]
f = s

[shift]
rightshift = toggle(shift)
capslock = clear()
i = S-o



[shiftextras:S]
d=S-t
a=S-n 
s=S-r 
f=S-s
e=S-d
g=S-V


[nav:C]
# Changed to extra layer
#h = left
#k = up
#j = down
#l = right
i = (
u = )
p = & 
o = *
compose = rightmouse

[vim:S]
j = pagedown
k = pageup
h = macro(15zh)
l = macro(15zl)
o = macro(C-z)
i = {
u = }
tab = macro(C-tab)

[extra]
h = left
k = up
j = down
l = right
i = =
o = macro(S-=)
u = $
r = ^
p = %
n = macro(C-v)
m = macro(C-c)
; = macro(f12)

[controlextra:C]
j = C-tab
k = macro(S-C-tab)
u = 6
i = 7
o = 8
p = 9
[ = 0

[nums]

[togglerandom]
# w=w
# a=a
# s=s
# d=d
i = o
a = n
s = r
d = t
#f = s
e = d
g = v
w = l
# x = f3
leftshift = layer(shift)
capslock=esc

[toggleautoclick]
leftalt = leftmouse
#leftmouse = rightmouse

[w_extras]
w = l
i = [
u = ] 
j = pagedown
k = pageup
n = macro(C-S-v)
m = macro(C-S-c)

[nodelete]
backspace = noop
